### ISSUE TITLE
DigitalNoted not found

### ISSUE THREAD

**Issue by anastaviki** [rubber-duckie-au/xdn-installer#1]
After install master node i try to run it and "DigitalNoted command not found"

**Comment by rubber-duckie-au** [comment]
Hi, yeah the script needs to be updated to match new DigitalNote fork. I will update as soon as I can, please see updated instructions on readme.

**Comment by anastaviki** [comment]
This intruction also for master node?

**Comment by rubber-duckie-au** [comment]
Yep, you will also need to manually update your DigitalNote.conf file with:
listen=1
server=1
daemon=1
masternode=1
externalip=external ip
masternodeaddr=external ip:port
masternodeprivkey=priv key generated from instructions

**Comment by anastaviki** [comment]
Thank you
